kodi-pvr/pvr.hts

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/client.cpp
src/client.h

it's not being used, and it got changed in Kodi
fixes build failure

fixed: removed guilib dep

---

src/HTSPTypes.h

Boring stuff ... but senseful, imo.

[performance] ctors: initializer list vs. assignment.

---

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/HTSPTypes.h
src/Tvheadend.cpp

https://github.com/kodi-pvr/pvr.hts/issues/13
https://github.com/kodi-pvr/pvr.hts/issues/14
Please test and report back.
Note: changelog.txt already contains description for the other PRs I want to include in 2.1.6 (#10, #11, #15)

PVR addon API 1.9.6 changes

---

CMakeLists.txt
src/HTSPTypes.cpp
src/HTSPTypes.h
src/Tvheadend.cpp
src/Tvheadend.h
src/client.cpp

Added support for radio channel groups.
Please note that this feature relies on a Kodi fix. https://github.com/xbmc/xbmc/pull/6755

Added support for radio channel groups.

---

CMakeLists.txt
debian/control
src/AsyncState.h
src/CircBuffer.h
src/HTSPConnection.cpp
src/HTSPDemuxer.cpp
src/HTSPTypes.h
src/HTSPVFS.cpp
src/Tvheadend.cpp
src/Tvheadend.h
src/client.cpp
src/client.h

goes with https://github.com/xbmc/kodi-platform/pull/5

updated to use libplatform

---

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/HTSPTypes.h
src/Tvheadend.cpp

Latest tvheadend supports epg subtites (episode names):
https://github.com/tvheadend/tvheadend/commit/8dbc38df4a5cd85be243e77e1ebdd43dfe6e2683

Add support for epg subtitle (episode name).

---

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/HTSPConnection.cpp
src/Tvheadend.h
src/client.cpp

Lower required HTSP version to 10 (allows tvh 3.4 again).

---

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/Tvheadend.cpp

https://github.com/kodi-pvr/pvr.hts/pull/56

backport of #56 to Isengard

---

debian/kodi-pvr-hts.install

[debian packaging]: fix library install path

---

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/client.cpp

Add-on part of https://github.com/xbmc/xbmc/pull/7536

Bump add-on for PVR API 2.1.0 (already implemented, let's use it)

---

pvr.hts/addon.xml
pvr.hts/changelog.txt
src/HTSPConnection.cpp
src/HTSPTypes.h
src/HTSPVFS.cpp
src/Tvheadend.cpp
src/Tvheadend.h
src/client.cpp

@ksooo can you review? I've only build-tested so far.

drop CStdString

---

pvr.hts/changelog.txt
src/AutoRecordings.cpp
src/HTSPTypes.cpp
src/HTSPTypes.h

Runtime-tested by me and @PhobosK.
@Jalle19 Any objections?

Autorec: Fix handling of start end stop time.

---

pvr.hts/changelog.txt
pvr.hts/resources/language/resource.language.en_gb/strings.po
src/HTSPDemuxer.cpp
src/HTSPTypes.h
src/Tvheadend.cpp
src/Tvheadend.h

Found some issues with predictive tuning when working on the subscription conflict stuff.

Predictive tuning fixes

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt

Add-on part of https://github.com/xbmc/xbmc/pull/7570

Automatically fill in platform and library name

---

pvr.hts/changelog.txt
src/Tvheadend.cpp

don't treat "channel" as required in dvrEntryAdd messages, fixes #74

---

CMakeLists.txt
src/AutoRecordings.cpp
src/HTSPConnection.cpp
src/HTSPDemuxer.cpp
src/Tvheadend.cpp
src/Tvheadend.h
src/client.cpp
src/client.h
src/tvheadend/Settings.cpp
src/tvheadend/Settings.h
src/tvheadend/entity/AutoRecording.cpp
src/tvheadend/entity/Entity.h

Fixes Coverity complaints after https://github.com/kodi-pvr/pvr.hts/commit/f013946b78e5b4770316883edfdf8028140d7d0a @Jalle19 mind taking a look.
BTW: I overlooked the public members in class Settings you've just introduced. I do not like that, tbh and would have bugged you with that if I had seen this before the merge. ;-)

Refactor class Settings, step 2

---

CMakeLists.txt
src/Tvheadend.cpp
src/Tvheadend.h
src/tvheadend/ChannelTuningPredictor.cpp
src/tvheadend/ChannelTuningPredictor.h

@ksooo this is still WIP (the current commit works though) but you might wanna take a look.

Predictive tuning improvements

---

CMakeLists.txt
pvr.hts/resources/language/resource.language.en_gb/strings.po
src/HTSPDemuxer.cpp
src/HTSPTypes.h
src/Tvheadend.h
src/tvheadend/Subscription.cpp
src/tvheadend/Subscription.h

Subscription rework

---

src/Tvheadend.cpp

Fix recording state parsing

---

pvr.hts/changelog.txt
src/AutoRecordings.cpp
src/TimeRecordings.cpp
src/Tvheadend.cpp
src/Tvheadend.h
src/tvheadend/entity/Recording.h
src/tvheadend/entity/RecordingBase.cpp
src/tvheadend/entity/RecordingBase.h

From htsp v24 and on, it's possible to use lifetime where it's designed for :p

Remove actual file when lifetime expires

---

pvr.hts/changelog.txt
src/tvheadend/Settings.cpp
src/tvheadend/Settings.h

Settings fixes

---

pvr.hts/changelog.txt
src/HTSPDemuxer.cpp
src/tvheadend/Subscription.h

https://github.com/kodi-pvr/pvr.hts/issues/135

Fix for  #135

---

src/HTSPDemuxer.cpp
src/tvheadend/Subscription.cpp

@Glenn-1990 can you comment on the second commit? I don't see why we should log something if it's not fatal (we don't return).

Change some log levels

---

CMakeLists.txt
src/tvheadend/utilities/Logger.cpp
src/tvheadend/utilities/Logger.h

@ksooo this fixes the latest Coverity complaint (at least I hope so).

Minor logger improvements

---

.travis.yml
README.md

Run automatic build tests on Travis CI

---

src/tvheadend/utilities/Logger.cpp
src/tvheadend/utilities/Logger.h

fixed crash in logger on windows.

---

CMakeLists.txt
src/AutoRecordings.cpp
src/HTSPConnection.cpp
src/HTSPDemuxer.cpp
src/HTSPVFS.cpp
src/TimeRecordings.cpp
src/Tvheadend.cpp
src/Tvheadend.h
src/client.cpp
src/client.h
src/tvheadend/Subscription.cpp
src/tvheadend/Subscription.h
src/tvheadend/utilities/AsyncState.cpp
src/tvheadend/utilities/AsyncState.h

Supersedes https://github.com/kodi-pvr/pvr.hts/pull/154
Builds with cmake and debuild. Not runtime tested.

Update to libp8-platform

---

CMakeLists.txt

Decided to move these commits to a separate PR instead of polluting #180.

Add missing files to CMakeLists.txt

---

src/HTSPDemuxer.cpp
src/Tvheadend.h

@adamsutton are you able to comment on whether https://github.com/kodi-pvr/pvr.hts/commit/e61ad9d5aec5e3582767d14452654b31a06de00d looks correct?

Fix some potential threading issues in the demuxer

---

.travis.yml
CMakeLists.txt
pvr.hts/addon.xml.in
pvr.hts/changelog.txt
pvr.hts/resources/language/resource.language.af_za/strings.po
pvr.hts/resources/language/resource.language.fr_ca/strings.po
pvr.hts/resources/language/resource.language.gl_es/strings.po
src/HTSPDemuxer.cpp
src/Tvheadend.h

I adapted travis.yml to build against the Kodi Jarvis branch, let's see how it goes.

Jarvis backports

---

src/Tvheadend.cpp
src/Tvheadend.h

Ddrop unused GetStreamingProfile() method

---

src/HTSPDemuxer.cpp

HTSPDemuxer: fix m_seekTime race in CHTSPDemuxer::Seek

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/HTSPConnection.cpp
src/Tvheadend.cpp
src/Tvheadend.h

@Jalle19 mind taking a look.
@FernetMenta I fixed travis build with this PR, no need for you to do it.

Support for PVR API 5.1.1 and minor fixes

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/tvheadend/ChannelTuningPredictor.cpp

Fix crash on initial predictive tuning

---

.travis.yml

tinyxml requires at least CMake 3.1

Fix Travis XCode 6.1 build by upgrading CMake

---

.travis.yml

Reference: https://github.com/kodi-pvr/pvr.hts/pull/242#issuecomment-248836422

Drop duplicate "script: make" from .travis.yml

---

.travis.yml
README.md
appveyor.yml

Should fix builds on the master branch. Closes #265

fix path to cmake/addons in .travis.yml

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/Tvheadend.cpp

Fix CTvheadend::DemuxIsTimeShifting() after #275
@Glenn-1990 okay?

Fix CTvheadend::DemuxIsTimeShifting()

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/Tvheadend.cpp

Fix CTvheadend::DemuxIsTimeShifting() after #276
@Glenn-1990 okay?

Krypton: Fix CTvheadend::DemuxIsTimeShifting()

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/Tvheadend.cpp
src/Tvheadend.h
src/client.cpp
src/tvheadend/entity/Recording.h

@ksooo Revert playcount/playposition

Revert "[htsp v26] implement server based playcount and playposition"

---

debian/kodi-pvr-hts.install

This also affects Krypton. After view, please merge into the Krypton branch as well.

fix install path

---

pvr.hts/addon.xml.in
src/Tvheadend.h
src/client.cpp
src/client.h
src/xbmc_codec_descriptor.hpp

Related to Kodi Pull Request xbmc/xbmc#12028 where libXBMC_codec.h becomes removed.

libXBMC_codec.h removed and changed to libXBMC_pvr.h

---

CMakeLists.txt
pvr.hts/addon.xml.in
pvr.hts/changelog.txt

Related to kodi Pull Request xbmc/xbmc#12029
Not merge in before is in Kodi!

change to automatic depends set on addon.xml

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/client.cpp

related to Kodi pull request xbmc/xbmc#12109

remove no more needed version functions

---

debian/control
pvr.hts/addon.xml.in
pvr.hts/changelog.txt

This is related to xbmc/xbmc#12114 and xbmc/xbmc#12116

Update addon Version related to Kodi changes

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
pvr.hts/resources/language/resource.language.en_gb/strings.po
src/HTSPTypes.h
src/Tvheadend.cpp
src/tvheadend/Settings.h

Fixes #311, superseeds #312 
@DocMAX fyi, maybe you can even runtime test this?

Add support for 'default' recording priority setting value. Fixes #311, closes #312

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/client.cpp

https://github.com/xbmc/xbmc/pull/12552

api 5.4.0 - drop SwitchChannel

---

CMakeLists.txt
pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/AutoRecordings.cpp
src/HTSPConnection.cpp
src/HTSPDemuxer.cpp
src/TimeRecordings.cpp
src/Tvheadend.cpp
src/Tvheadend.h
src/tvheadend/Subscription.cpp
src/tvheadend/utilities/LocalizedString.h

Some trivial, but useful/important stuff.
@Jalle19 mind taking a look?

Misc fixes.

---

src/tvheadend/entity/Tag.cpp

Fix windows build (missing ssize_t type definition), take 3.

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/Tvheadend.cpp
src/tvheadend/entity/Recording.h

4.2.12: Recordings improvements

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
pvr.hts/resources/language/resource.language.en_gb/strings.po
pvr.hts/resources/settings.xml
src/client.cpp
src/tvheadend/Settings.cpp
src/tvheadend/Settings.h

PVR Addon API 5.10.0: Implement stream read chunk size as addon setting.

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/Tvheadend.cpp
src/tvheadend/HTSPConnection.cpp
src/tvheadend/HTSPDemuxer.cpp

Add support for recent tvheadend 4.3 image URL changes (HTSP v34)

---

pvr.hts/addon.xml.in
pvr.hts/changelog.txt
src/tvheadend/HTSPDemuxer.cpp
src/tvheadend/HTSPDemuxer.h

Requires Kodi fix: https://github.com/xbmc/xbmc/pull/14488
Code taken from https://github.com/FernetMenta/pvr.hts/commit/9999beb87dab709689384f1fe03b65e8f2a01a63 Details discussed there.

4.4.15: demuxer timeshift improvements
